### PR TITLE
docs: Fixed info blocks, moved formatting guide, and added email settings settings guide

### LINKED ISSUE #699: Documentation formatting fixes and content update
- Fix broken formatting
     - Data Settings
     - CORS Settings
     - Auth Settings
     - Webhooks Guide
     - Session Bridge
     - External Authorization
     - API Permission Ref
     - POTSGRE JSONB Migration
     - Design and architecture
- Add technical guide for SMTP
- Add end-user docs for formatting expression functions

### PR DESCRIPTION
**Pull request by orilux**
## Description

- Fixed formatting of blocks that were broken by changes in Docusaurus 3
- Moved the end-user doc on formatting functions to the expressions page for consistency
- Added settings doc on configuring email providers

## Type of Change
Check all that apply.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Dependency update
- [ ] Refactoring (non-breaking change which improves code quality)
- [ ] Other (please describe)

## Checklist
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

> [!NOTE]
> - [x] I confirm that my Pull Request follows all the checklist requirements above

### CODE REVIEW

File: docs/endatix-docs/sidebars.ts [hunk 1]
```diff
@@ -101,6 +101,7 @@ const sidebars: SidebarsConfig = {
             "configuration/settings/auth-settings",
             "configuration/settings/cors-settings",
             "configuration/settings/data-settings",
+            "configuration/settings/email-provider-settings",
```
Comment (PeterMarinov) [inline docs/endatix-docs/sidebars.ts]: naming consistency: for the filename, why not rename the file to email-settings? All other Urls follow this pattern? You can still keep the same page title - just make the Url shorter

File: docs/endatix-docs/docs/configuration/settings/email-settings.mdx [hunk 2]
```diff
@@ -0,0 +1,118 @@
+---
+sidebar_position: 4
+title: Email Provider Settings
+---
+
+# Email Provider Settings
+
+Endatix requires an email provider to send transactional emails, form submission notifications, and identity verification links (like password resets). Out of the box, the Endatix API supports **SendGrid**, **Mailgun**, and standard **SMTP**.
+
+Configuration is managed via your `appsettings.json` file or environment variables under the `Endatix:Integrations:Email` section.
```
Comment (PeterMarinov) [inline docs/endatix-docs/docs/configuration/settings/email-settings.mdx:10]: It's great that we list the settings, but developers don't have all the info they need on how to activate the Email provider. **We don't have to change this now, but consider this:**

They need to modify their `Program.cs` and call ConfigureEndatixWithDefaults pointing which Email provider to use e.g.

```cs
builder.Host.ConfigureEndatixWithDefaults(endatix =>
{
    endatix.Infrastructure.Integrations.AddEmail<MailgunEmailSender, MailgunSettings>();
});
```

With that said, I think we need to:
1. Maybe add high level guide on configuring email under guides or building-your-solution. Goal: quickly see supported options and reference to the how-tos if reader needs to dive deeper - **dunno where exactly yet**
2. Move endatix-api specific settings and guides like modifying the Program.cs and the appSettings config under endatix-api developer documentation

**Review by PeterMarinov — DISMISSED** [review]
I am approving with request to rename the email settings file and adding some thoughts on improving the structure of the docs, now that we have endatix-api and endatix-hub specific developer sections

File: docs/endatix-docs/docs/configuration/settings/email-settings.mdx (hunk 2 above)
Comment (orilux) [reply docs/endatix-docs/docs/configuration/settings/email-settings.mdx:10]: Created the guide

**Review by PeterMarinov — APPROVED** [review]

File: docs/endatix-docs/docs/configuration/settings/email-settings.mdx (hunk 2 above)
Comment (PeterMarinov) [reply docs/endatix-docs/docs/configuration/settings/email-settings.mdx:10]: Cool
